CREATE DATABASE STUDENT_DATABASE_PROJECT;
USE STUDENT_DATABASE_PROJECT;
CREATE TABLE STUDENTS (
	STUDENT_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    ADDRESS VARCHAR(50),
    CITY VARCHAR(50),
    STATE CHAR(2),
    ZIP_CODE CHAR(5)
    );
SHOW TABLES;
CREATE TABLE DEPARTMENT (
	DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE
    );
CREATE TABLE INSTRUCTOR (
	INSTRUCTOR_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) 
    );
CREATE TABLE COURSE (
	COURSE_ID INT PRIMARY KEY,
    COURSE_NUM VARCHAR(10) NOT NULL,
    COURSE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    CREDIT_HOURS INT NOT NULL,
    INSTRUCTOR_ID INT,
    DEPT_ID INT,
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR(INSTRUCTOR_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
    );
    USE STUDENT_DATABASE_PROJECT;
CREATE TABLE ENROLLMENT (
	ENROLLMENT_ID INT PRIMARY KEY,
    ENROLLMENT_DATE DATE NOT NULL,
    SEMESTER VARCHAR(15) NOT NULL,
    GRADE VARCHAR(2),
    STUDENT_ID INT,
    COURSE_ID INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
    );
ALTER TABLE STUDENTS DROP COLUMN ADDRESS;
ALTER TABLE STUDENTS DROP COLUMN CITY;
ALTER TABLE STUDENTS DROP COLUMN STATE;
ALTER TABLE STUDENTS DROP COLUMN ZIP_CODE;
