CREATE DATABASE STUDENT_DATABASE_PROJECT;
USE STUDENT_DATABASE_PROJECT;
CREATE TABLE STUDENTS (
	STUDENT_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    ADDRESS VARCHAR(50),
    CITY VARCHAR(50),
    STATE CHAR(2),
    ZIP_CODE CHAR(5)
    );
SHOW TABLES;
CREATE TABLE DEPARTMENT (
	DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE
    );
CREATE TABLE INSTRUCTOR (
	INSTRUCTOR_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) 
    );
CREATE TABLE COURSE (
	COURSE_ID INT PRIMARY KEY,
    COURSE_NUM VARCHAR(10) NOT NULL,
    COURSE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    CREDIT_HOURS INT NOT NULL,
    INSTRUCTOR_ID INT,
    DEPT_ID INT,
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR(INSTRUCTOR_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
    );
    USE STUDENT_DATABASE_PROJECT;
CREATE TABLE ENROLLMENT (
	ENROLLMENT_ID INT PRIMARY KEY,
    ENROLLMENT_DATE DATE NOT NULL,
    SEMESTER VARCHAR(15) NOT NULL,
    GRADE VARCHAR(2),
    STUDENT_ID INT,
    COURSE_ID INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
    );
ALTER TABLE STUDENTS DROP COLUMN ADDRESS;
ALTER TABLE STUDENTS DROP COLUMN CITY;
ALTER TABLE STUDENTS DROP COLUMN STATE;
ALTER TABLE STUDENTS DROP COLUMN ZIP_CODE;
SELECT *
	FROM STUDENTS;
INSERT INTO STUDENTS VALUES 
(1001, 'Maya', 'Johnson', '1995-03-15'),
(1002, 'Ethan', 'Carter', '1994-11-22'),
(1003, 'Sophia', 'Nyguyen', '1996-07-09'),
(1004, 'Noah', 'Martinez', '1995-01-30'),
(1005, 'Ava', 'Thompson', '1994-09-18');
SELECT *
	FROM STUDENTS;
ALTER TABLE DEPARTMENT DROP COLUMN LAST_NAME;
ALTER TABLE DEPARTMENT DROP COLUMN EMAIL;
ALTER TABLE DEPARTMENT MODIFY DEPT_NAME VARCHAR(100);
INSERT INTO DEPARTMENT VALUES
(101, 'Computer Science'),
(102, 'Mathematics'),
(103, 'Biology'),
(104, 'Business Administration'),
(105, 'Engineering'),
(106, 'Psychology'),
(107, 'English'),
(108, 'Chemistry');
SELECT *
	FROM DEPARTMENT;
INSERT INTO INSTRUCTOR VALUES
(491, 'Sara', 'Mitchell', 's.mitchell@email.com', 101),
(138, 'Lilly', 'Campbell', 'l.campbell@email.com', 102),
(864, 'David', 'Anderson', 'd.anderson@email.com', 103),
(142, 'Michael', 'Thompson', 'm.thompson@email.com', 104),
(890, 'Jennifer', 'Williams', 'j.williams@email.com', 101),
(545, 'Angela', 'Brown', 'a.brown@email.com', 105),
(439, 'Kevin', 'Wilson', 'k.wilson@email.com', 106),
(719, 'Freddie', 'Ross', 'f.ross@email.com', 107);
SELECT *
	FROM INSTRUCTOR;
INSERT INTO COURSE VALUES
(301, 'CS101', 'Intro to Programming', 'Programming fundamentals', '3', 491, 101),
(302, 'MATH201', 'Calculus 1', 'Introduction to calculus concepts', '4', 138, 101),
(303, 'BIO110', 'Biology Basics', 'Fundamentals of biological science', '4', 864, 101),
(304, 'BUS120', 'Business Management', 'Principles of business operations', '3', 142, 101),
(305, 'CS220', 'Database Systems', 'Relational databases and SQL concepts', '3', 890, 101),
(306, 'CHEM101', 'General Chemistry', 'Basic chemistry principles', '4', 545, 101),
(307, 'PSY101', 'Psychology Fundamentals', 'Introduction to human behavior', '3', 439, 101),
(308, 'ENG101', 'English Composition', 'College writing and communication', '3', 719, 101);
SELECT *
	FROM COURSE;
INSERT INTO ENROLLMENT VALUES
(01, '2013-08-20', 'Fall', 'A', 1001, 301),
(02, '2013-08-20', 'Fall', 'B+', 1002, 302),
(03, '2014-01-13', 'Spring', 'A-', 1003, 303),
(04, '2013-09-03', 'Fall', 'B', 1004, 304),
(05, '2012-08-27', 'Fall', 'A', 1005, 305),
(06, '2014-01-13', 'Spring', 'B+', 1001, 302),
(07, '2014-08-25', 'Fall', 'A-', 1002, 301),
(08, '2015-01-12', 'Spring', 'B', 1003, 306);
SELECT *
	FROM ENROLLMENT;
UPDATE COURSE
	SET DEPT_ID = 101
		WHERE COURSE_ID = 301;
UPDATE COURSE
	SET DEPT_ID = 102
		WHERE COURSE_ID = 302;
UPDATE COURSE
	SET DEPT_ID = 103
		WHERE COURSE_ID = 303;
UPDATE COURSE
	SET DEPT_ID = 104
		WHERE COURSE_ID = 304;
UPDATE COURSE
	SET DEPT_ID = 101
		WHERE COURSE_ID = 305;
UPDATE COURSE
	SET DEPT_ID = 105
		WHERE COURSE_ID = 306;
UPDATE COURSE
	SET DEPT_ID = 106
		WHERE COURSE_ID = 307;
UPDATE COURSE
	SET DEPT_ID = 107
		WHERE COURSE_ID = 308;
SELECT COURSE_ID, COURSE_NAME, DEPT_ID
	FROM COURSE;
-- List every student and their date of birth.
SELECT FIRST_NAME, LAST_NAME, DATE_OF_BIRTH
	FROM STUDENTS;
-- List all courses in alphabetical order by course name.
SELECT COURSE_NAME
	FROM COURSE
		ORDER BY COURSE_NAME;
-- Show all instructors who belong to the Computer Science department.
SELECT FIRST_NAME, LAST_NAME
	FROM INSTRUCTOR
		WHERE DEPT_ID = '101';
-- Show all students born after January 1, 1995.
SELECT FIRST_NAME, LAST_NAME
	FROM STUDENTS
		WHERE DATE_OF_BIRTH > '1995-01-01';
-- Count the total number of students.
SELECT COUNT(*)
	FROM STUDENTS;
-- Count how many courses each department offers.
SELECT DEPT_ID, COUNT(*) AS COURSE_COUNT
	FROM COURSE
		GROUP BY DEPT_ID;
-- Calculate the average credit hours of all courses.
SELECT AVG(CREDIT_HOURS) AS AVERAGE_CREDIT_HOURS
	FROM COURSE;
-- Find the department that offers the most courses.
SELECT DEPT_ID, COUNT(*) AS COURSE_COUNT
	FROM COURSE
	GROUP BY DEPT_ID
	ORDER BY COURSE_COUNT DESC
	LIMIT 1;
-- List every student along with the courses they are enrolled in.
SELECT STUDENTS.FIRST_NAME, STUDENTS.LAST_NAME, COURSE.COURSE_NAME
	FROM STUDENTS
	JOIN ENROLLMENT
	ON STUDENTS.STUDENT_ID = ENROLLMENT.STUDENT_ID
	JOIN COURSE
	ON ENROLLMENT.COURSE_ID = COURSE.COURSE_ID;
-- List every instructor and the courses they teach.
SELECT STUDENTS.FIRST_NAME, STUDENTS.LAST_NAME, COURSE.COURSE_NAME
	FROM STUDENTS
	JOIN ENROLLMENT
	ON STUDENTS.STUDENT_ID = ENROLLMENT.STUDENT_ID
	JOIN COURSE
	ON ENROLLMENT.COURSE_ID = COURSE.COURSE_ID;
-- Show every department.
SELECT *
	FROM DEPARTMENT;
-- Find all students enrolled in courses worth more than 3 credit hours.
SELECT STUDENTS.FIRST_NAME, STUDENTS.LAST_NAME, COURSE.COURSE_NAME, COURSE.CREDIT_HOURS
	FROM STUDENTS
	JOIN ENROLLMENT
	ON STUDENTS.STUDENT_ID = ENROLLMENT.STUDENT_ID
	JOIN COURSE
	ON ENROLLMENT.COURSE_ID = COURSE.COURSE_ID
		WHERE COURSE.CREDIT_HOURS > 3;
-- Find the instructor(s) teaching the course with the highest number of credit hours.
SELECT FIRST_NAME, LAST_NAME
	FROM INSTRUCTOR
		WHERE INSTRUCTOR_ID IN (SELECT INSTRUCTOR_ID
									FROM COURSE
										WHERE CREDIT_HOURS =
											(SELECT MAX(CREDIT_HOURS)
												FROM COURSE));
-- Create a view that displays each students full name, course name, semester, and grade. STUDENT, COURSE, ENROLLMENT
CREATE VIEW STDT (FN,CN,S,G) AS
	SELECT CONCAT(STUDENTS.FIRST_NAME, ' ', STUDENTS.LAST_NAME), COURSE.COURSE_NAME, ENROLLMENT.SEMESTER, ENROLLMENT.GRADE
		FROM STUDENTS
        JOIN ENROLLMENT
		ON STUDENTS.STUDENT_ID = ENROLLMENT.STUDENT_ID
        JOIN COURSE
        ON ENROLLMENT.COURSE_ID = COURSE.COURSE_ID;
-- A UNIQUE constraint automatically creates an index in MySQL. I just wanted to showcase skill. Indexing speeds up the searching process in a table.
CREATE INDEX INSTRUCTOR_EMAIL
	ON INSTRUCTOR(EMAIL);

		